name: SIG Reviewer/Maintainer Nomination Template
description: Nominate yourself or someone else to become a SIG reviewer or maintainer.
title: 'SIG Reviewer/Maintainer Nomination'
body:
  - type: markdown
    attributes:
      value: |
        The Documentation and Community SIG maintains several reviewer roles requiring SIG approval:

        * **Documentation reviewer** - Documentation reviewers review for conformance with the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/), appropriateness of content, and other subjective factors to keep documentation content aligned.
        * **Technical reviewer** - Technical reviewers review documentation for technical accuracy: They make sure that described steps, features, file formats, code examples, and other parts of documentation that are deeply technical match the _current_ product state.

        Any individual can be a member of multiple reviewer or maintainer roles within this SIG!

        For more on the general requirements of Reviewer and Maintainer roles, read our [Community Membership](https://github.com/o3de/community/blob/main/community-membership.md) information.

        ----
        <!-- CUT ABOVE THIS LINE BEFORE POSTING -->
        ### Nomination Guidelines

        #### Documentation reviewer

        * [ ] 6+ documentation contributions merged to o3de.org or O3DE. The following count as documentation contributions:
          * Contributions to the Atom Guide, User Guide, Welcome Guide, or Tutorials sections of https://o3de.org/docs
          * High-quality error messages, tooltips, UX text, or API documentation submitted to https://github.com/o3de/o3de involving approval of
            at least one sig-docs-community reviewer.
        * [ ] 2+ Reviewers or Maintainers of the Documentation and Community SIG approve the nomination.

        **Maintaining status:** 4+ Pull Requests reviewed per month, or as-assigned. Light loads of PRs relax these requirements.

        #### Technical reviewer

        * [ ] Is a Reviewer or Maintainer for a SIG governing the appropriate technology.
        * [ ] 1+ of the appropriate SIG's Reviewers or Maintainers who support the promotion.
        * [ ] 1+ Reviewers or Maintainers of the Documentation and Community SIG who support the promotion.

        **Maintaining status:** Serve in the technical review rotation for your SIG as required by their available pool of reviewers.

        #### Documentation maintainer

        * [ ] Has been a Reviewer for 2+ months
        * [ ] 12+ reviewed Pull Requests in the previous 2 months (exceptions may be made during periods of light load)
        * [ ] 2+ Documentation and Community SIG Maintainers who support promotion. In the absence of enough maintainers, chairs will promote.

        **Maintaining status:** 8+ Pull Requests reviewed per month. Maintainers are encouraged to attend SIG triage and other regular meetings.

        -------
        ### Reviewer/Maintainer Nomination

        ##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
        -------------------

        I would like to nominate: ***<GitHub User Name>***, to become a ***<Docs Reviewer|Technical Reviewer|Maintainer>*** on behalf of ***sig-<SIG Name>***. I verify that they have fulfilled the prerequisites for this role.

        * Nominee's GitHub Profile ***< https://github.com/ githubsername >***

        *Reviewers & Maintainers that support this nomination should comment in this issue.*
